### PR TITLE
Setup my MV Project Pull request

### PR DESCRIPTION
**Pull request by Hsuwaddyhtat22**
Thank you Microverse

### CODE REVIEW

**Comment by Hsuwaddyhtat22** [comment]
Thanks

**Review by topeogunleye — COMMENTED** [review]
Hi @Hsuwaddyhtat22, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

Try-Again

> ## (Highlights) Good Points: 💪 
> * No linter errors ✔️ 
> * Committed: an `.html` and `.css` file ✔️ 
> * listed node_modules in `.gitignore` ✔️ 
> * listed test.md in `.gitignore` ✔️ 

## Required Changes ♻️
_Check the comments under the review._

- [x] You have submitted a merged pull request, Kindly make sure you do not merge your PR until it is approved. Please revert your merge and resubmit your pull request. You can use the `git revert` command to undo the merge. Please let me know if you need any help with this.

I also want to remind you that this is a serious violation of the code review guidelines. If you merge your PR before approval in the future, your submission will be invalidated and you will not receive feedback or credit for your work.

- [ ] In the case of README consider not leaving out any of the sections in the [Microverse README](https://github.com/microverseinc/readme-template) template as it's a project requirement.

| professional Readme  | Your Readme that is not professional |
| ------------- | ------------- |
|  Recording 2023-02-14 at 12 52 20 (5)	  | image |

- [ ] Please kindly add a more descriptive PR title and description as seen in the demo below:

`Setup my MV Project Pull request` and `Thank you Microverse` is not descriptive of the changes made in this branch

pull_request_desc

- [ ] I have a suggestion for improvement on your branch name `master`.

Your branch name dev does not follow the convention of being named after the feature or action that you implemented. For example, if you added Hello Microverse, you could name your branch `feature/added-Hello-Microverse`. This makes it easier to track the changes and the purpose of each branch.

I recommend that you checkout to a new branch with a more descriptive name and resubmit your pull request. Please mention the old PR number in the new PR description so that reviewers can see the connection.

- [ ] Next time, and for future commits, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Bad Commit Messages :x:
image

**Comment by Hsuwaddyhtat22** [comment]
I don't know about git revert. Can you explain me a little more?

**Comment by topeogunleye** [comment]
> I don't know about git revert. Can you explain me a little more?

You should see a button that says revert merge on Github. You can do it on Github

@Hsuwaddyhtat22 

image

**Pull request merged**
